name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore "MyStoreAPI/MyStoreAPI.csproj"

      - name: Build
        run: dotnet build "MyStoreAPI/MyStoreAPI.csproj" --configuration Release --no-restore

      - name: Run tests
        run: dotnet test "MyStoreAPI/MyStoreAPI.csproj" --no-build --verbosity normal

      - name: Build Docker image
        run: docker build -t manpreets115/mystoreapi:dev .

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push manpreets115/mystoreapi:dev

      - name: Run Docker container
        run: docker run -d -p 8080:80 manpreets115/mystoreapi:dev
